export const copy = {
  en: {
    app: "PUNCH",
    tag: "Show up. Get paid. See who keeps what.",
    connectTitle: "Get paid to show up.",
    connectBody:
      "Small real-world jobs on your Seeker phone. You are paid in digital dollars. Everyone sees the cut. No hidden fee.",
    connectCta: "Open my wallet",
    connecting: "Opening wallet…",
    clockIn: "CLOCK IN",
    nexusLine: "Nexus pays presence.",
    ticketIn: "IN",
    ticketRule: "92 / 3 / 5 on every job",
    lblTime: "TIME",
    lblCountry: "COUNTRY",
    lblSplit: "SPLIT",
    guideSkip: "Skip — open the app",
    guideNext: "Next",
    guideBack: "Back",
    guideStart: "Start the tour",
    guideDone: "That's the whole app",
    g8go: "Seal",
    identity: "Identity",
    identityTag: "The app wears ONE color. Gold is the original; Nuit is the moon.",
    identityGold: "Gold Seeker Premium",
    identityGoldSub: "The original — warm black, true gold, ivory tickets",
    identityNuit: "Seeker Nuit",
    identityNuitSub: "The option — blue-black, moon silver, slate tickets",
    look: "Look",
    lookTag: "The app's design — monolith + tickets, one way to be shown.",
    lookFixed: "Seeker Premium · B+C fusion",
    lookWorn: "Worn",
    lookApplied: "You wear the identity",
    skin3dTitle: "Vector relief",
    skin3dTag: "Same design, in volume — metal bevels, floating dial, paper shadow.",
    skin3dFlat: "Flat — the heritage: raw angles, flush surfaces",
    skin3dDepth: "3D — metal bevels, floating dial, paper shadow",
    g1t: "CLOCK IN",
    g1b: "Seekers hunt. Nexus is where they meet. Punch proves you showed up.",
    g2t: "One tap. You're here.",
    g2b: "Press the clock. A real Seeker, not a laptop.",
    g2go: "Tap the bolt",
    g3t: "Your ticket",
    g3b: "Country only. Never a street. The cut is printed on the card.",
    g4t: "Who keeps what",
    g4b: "Tap each number. No hidden fee.",
    g4w: "You — the person who showed up",
    g4s: "People who keep SKR",
    g4p: "Nexus — you, the creator",
    g5t: "The world",
    g5b: "A punch writes a country on the globe. Drag it. No GPS.",
    g5go: "Stamp France",
    g6t: "A job, then dollars",
    g6b: "A few minutes. Paid in USDC or USDT. Receipt is public.",
    g7t: "Say hi nearby",
    g7b: "Two Seekers. Ten cents each, paid from Nexus's 5%. A hello, not a farm.",
    g7go: "Say hi",
    g8t: "PLI is the other verb",
    g8b: "Sealing secrets — coming after CLOCK IN.",
    genesis: "This Seeker is verified",
    punch: "Home",
    board: "Jobs",
    wallet: "Money",
    split: "The cut",
    punchCta: "I'm here",
    punched: "You're in",
    boardUnlocked: "Jobs are open",
    streak: "Days in a row",
    days: "days",
    crew: "People here",
    today: "You earned",
    nextWindow: "Next check-in",
    demoNote: "In this demo you can check in again after a short wait. For real: once a day.",
    needPunch: "Tap I'm here to unlock today's jobs.",
    earlyAccess: "You see jobs a bit earlier",
    earlyAccessOff: "3 days in a row = you see jobs first",
    rankLine: "Keeping SKR does not print money. It lets you see the better-paid jobs first.",
    available: "Open",
    locked: "Locked",
    spots: "spots left",
    min: "min",
    startShift: "Do this job",
    lockedRank: "Keep more SKR to unlock",
    lockedGenesis: "Needs a real Seeker phone",
    posted: "You posted this",
    dwellCta: "I arrived",
    dwellHold: "Stay on this screen",
    reviewLabel: "What really worked or broke",
    reviewCta: "Send my note",
    reviewHint: "Write at least 40 characters. A star is not a review.",
    scanCta: "Scan the code",
    scanStep1: "Point at the code",
    scanStep2: "Phone is proving it's you",
    scanStep3: "You're confirmed",
    swapCta: "Make the exchange",
    watchCta: "Start the watch",
    watchHold: "Keep this screen open",
    complete: "Get paid",
    signing: "Confirming on the phone…",
    cashed: "Paid",
    receipt: "Receipt",
    gross: "Job total",
    worker: "You keep",
    stakers: "SKR holders",
    protocol: "This app",
    tx: "Proof",
    back: "Back",
    postShift: "Pay someone",
    postTitle: "Pay for a job",
    postBody:
      "You lock digital dollars. Someone with a Seeker does the job. Same rule: they keep 92%, holders 3%, the app 5%.",
    postCta: "Lock the money",
    title: "Job title",
    amount: "Pay",
    token: "Currency",
    city: "City",
    duration: "Minutes",
    fill: "Someone will take this soon.",
    fillCta: "Pretend someone took it",
    balances: "Your money",
    stake: "Keep SKR to rank up",
    unstake: "Release SKR",
    staked: "Kept",
    liquid: "Ready to use",
    rank: "Access",
    swap: "Change currency",
    from: "From",
    to: "To",
    spread: "Fee 0.35%",
    spreadSplit: "The small exchange fee is shown first. Half to the app, half to SKR holders.",
    youPay: "You pay",
    youGet: "You receive",
    swapFee: "Exchange fee",
    confirmSwap: "Exchange",
    stakeHint: "1,000 SKR = Silver. 5,000 = Gold. 25,000 = Guardian. Better jobs first — no extra printed money.",
    confirmStake: "Keep SKR",
    splitHero: "You keep 92%. Always.",
    splitBody:
      "On every paid job: 92% to the person who showed up, 3% to people who keep SKR, 5% to the app (that's the creator). No points. No surprise fee.",
    protocolTreasury: "App (creator)",
    stakerPool: "SKR holders",
    skrBought: "SKR bought with fees",
    yourWages: "You were paid",
    feeTable: "Every receipt",
    reset: "Start the demo over",
    pitch: "How we present it",
    live: "Demo · live",
    demoDataNote:
      "Demo network: nearby Seekers and the live feed are simulated. Check-ins, payments and balances are real, on-chain.",
    seekerOnly: "Made for the Seeker phone",
    demoVault: "Demo wallet. On a real Seeker the phone itself signs.",
    copyAddr: "Copied",
    notEnough: "Not enough money",
    tooShort: "A bit short",
    done: "Done",
    emptyBoard: "Nothing in this filter.",
    filterAll: "All",
    howTitle: "Three steps. That's the whole app.",
    how1b: "One tap a day. Your Seeker proves a real person showed up — not a robot on a laptop.",
    how2b: "Confirm a café is open, write an honest note, scan a stall. A few minutes. Paid in digital dollars.",
    how3b: "You keep 92%. SKR holders get 3%. The app keeps 5%. The receipt is public. That's how you and the creator both earn, honestly.",
    moneyUsdc: "USDC and USDT are digital dollars. One token ≈ one US dollar.",
    moneySkr: "SKR is the Seeker phone token. Keep it to see better jobs first. It does not print extra pay.",
    seeJobs: "See today's jobs",
    nearby: "Seekers near you",
    greet: "Say hi",
    greeted: "Said hi",
    greetPay: "You both get $0.10. Paid from the app's 5% — a hello, not a farm.",
    meters: "m away",
    themeDark: "Dark",
    themeLight: "Light",
    themeGold: "Gold Seeker Premium",
    themeGoldLight: "Gold light",
    paySomeone: "Pay someone",
    studio: "Two products. Same money rule.",
    studioTitle: "Two verbs. Not two copies.",
    punchPick: "Open PUNCH",
    punchPickBody: "You show up. You get paid.",
    pliPick: "Open PLI",
    pliPickBody: "You seal a secret. People pay to read it. The chain never does.",
    pliName: "PLI",
    pliTag: "A secret with a price. The chain is blind.",
    pliBox: "Inbox",
    pliWrite: "Seal",
    pliSealed: "Sealed",
    pliOpened: "Opened",
    pliWaiting: "Not yet",
    pliOpenCta: "Pay to read",
    pliOpening: "Unsealing on the phone…",
    pliRead: "Read again",
    pliPrice: "Price to open",
    pliFrom: "From",
    pliWriteTitle: "Seal a note",
    pliWriteBody:
      "Write something only a Seeker can unwrap. You are paid when someone buys it. Same cut: 92 / 3 / 5.",
    pliWriteCta: "Seal and list",
    pliWriteHint: "At least 24 characters. This text never sits in clear on the chain.",
    pliDelayNow: "Opens now",
    pliDelaySoon: "Opens in 1 min",
    pliMine: "Yours",
    pliSold: "Someone paid to read this",
    pliWaitingSell: "Waiting for a reader",
    pliLetter: "Unsealed",
    pliChain: "Solana saw the payment. It did not see this sentence.",
    pliEmpty: "No sealed notes here.",
    pliSeeBox: "Back to inbox",
    pliSoon: "Come back. The seal opens on its own.",
    atelier: "Both apps",
    pliCompte: "Ledger",
    pliConnectTitle: "The chain will not read this.",
    pliConnectCta: "Break the seal",
    punchEnter: "Enter PUNCH",
    pliEnter: "Enter PLI",
    globe: "World",
    globeTag: "Certified Seekers. Country only.",
    globePrivacy: "A punch writes a country. Never a street. Never a GPS point.",
    globeToday: "Punched today",
    globeAll: "Genesis / Seekers",
    globeYou: "You are on the map",
    globeNeed: "Punch in to stamp your country.",
    globeStamp: "On-chain stamp",
    globePick: "Your country (no address)",
    seeWorld: "See the world",
    globeLive: "Live stamps",
    punchCode: "Download PUNCH source",
    pliCode: "Download PLI source",
    settings: "Settings",
    settingsLanguage: "Language",
    settingsAppearance: "Appearance",
    settingsAccount: "Account",
    settingsAbout: "About",
    settingsWalletMode: "Wallet mode",
    settingsWalletReal: "Real Seed Vault",
    settingsWalletDemo: "Demo wallet",
    settingsResetConfirm: "Reset all demo data? This cannot be undone.",
    settingsVersion: "Version",
    netSection: "Network",
    netTag: "The public devnet RPC rate-limits. Plug in your own endpoint — your keys never leave your phone.",
    netPlaceholder: "https://your-endpoint.devnet...",
    netSave: "Save endpoint",
    netReset: "Back to public RPC",
    netTest: "Test connection",
    netTesting: "Testing…",
    netOk: (ms: number) => `Connection OK — ${ms} ms`,
    netFail: (why: string) => `Connection failed: ${why}`,
    netUsingCustom: "Custom endpoint active",
    netUsingDefault: "Public RPC active",
    netInvalid: "Enter a URL starting with https://",
    leaveNetwork: "Leave the network",
    leaveNetworkConfirm:
      "Leave the network? This signs a real transaction. You'll stop being counted, and you'll need to reconnect (a new transaction) to come back.",
    leaveNetworkFailed: "Transaction declined or failed — nothing was reset.",
    leaveNetworkHint: "Requires a signed Seed Vault transaction to confirm you're leaving.",
    realTxHint: "Real devnet transaction — Seed Vault will ask you to sign.",
    txFailed: "Transaction declined or failed — nothing changed.",
    needReconnect: "Session expired — open your wallet again to sign.",
    needSol: "Not enough SOL in your wallet for network fees. Top up and retry.",
    stakeLocked: "Locked in escrow",
    stakeFee: "Withdraw fee (1.5%)",
    stakeNet: "Net released",
    tapToWake: "Touch to wake up",
    settingsScreensaver: "Screensaver",
    screensaverOff: "Off",
    screensaverSecs: (n: number) => `${n}s`,
    cancel: "Cancel",
    confirm: "Confirm",
    openRanks: {
      open: "Open to all",
      silver: "Silver",
      gold: "Gold",
      guardian: "Guardian",
    },
    hellos: "Hellos",
    hellosTag: "Every hello counts. Your tally, week after week.",
    hellosWeek: "This week",
    hellosMonth: "This month",
    hellosYear: "This year",
    hellosTotal: "All time",
    hellosBoard: "Hello leaderboard",
    hellosYou: "You",
    hellosEarned: "SKR earned saying hi",
    hellosReward: "Each hello earns 25 SKR on top of your $0.10. Start-up bonus, not on-chain yet — when it is, it will be a real transaction.",
    hellosEmpty: "No hellos yet. Say hi to someone nearby.",
    hellosReset: "Counts reset on Monday, the 1st, and on New Year's Day.",
    history: "Ticket history",
    historyTag: "Every ticket you received — tap one to reopen it.",
    historyEmpty: "No tickets yet. Your first job or hello will land here.",
    stakerPaid: "SKR holders — your share",
    kinds: {
      dwell: "Be there",
      review: "Write",
      scan: "Scan",
      swap: "Exchange",
      watch: "Watch",
    },
  },
  fr: {
    app: "PUNCH",
    tag: "Tu te présentes. Tu es payé. On voit qui garde quoi.",
    connectTitle: "Sois là. Sois payé.",
    connectBody:
      "De petites missions autour de toi, sur le téléphone Seeker. Tu es payé en dollars numériques. La commission est affichée. Rien n'est caché.",
    connectCta: "Ouvrir mon portefeuille",
    connecting: "Ouverture du portefeuille…",
    clockIn: "CLOCK IN",
    nexusLine: "Nexus paie la présence.",
    ticketIn: "IN",
    ticketRule: "92 / 3 / 5 sur chaque mission",
    lblTime: "HEURE",
    lblCountry: "PAYS",
    lblSplit: "PART",
    guideSkip: "Passer — ouvrir l'app",
    guideNext: "Suivant",
    guideBack: "Retour",
    guideStart: "Commencer le mode d'emploi",
    guideDone: "C'est toute l'app",
    g8go: "Sceller",
    identity: "Identité",
    identityTag: "L'app porte UNE couleur. L'or est l'original ; la Nuit est la lune.",
    identityGold: "Gold Seeker Premium",
    identityGoldSub: "L'original — monolithe noir, or vrai, tickets ivoire",
    identityNuit: "Seeker Nuit",
    identityNuitSub: "L'option — noir bleuté, argent de lune, tickets ardoise",
    look: "Habillage",
    lookTag: "Le design de l'app — monolithe + tickets, une seule façon d'être affiché.",
    lookFixed: "Seeker Premium · Fusion B+C",
    lookWorn: "Porté",
    lookApplied: "Tu portes l'identité",
    skin3dTitle: "Relief vectoriel",
    skin3dTag: "Le même design, en volume — biseaux métal, cadran flottant, ombre papier.",
    skin3dFlat: "À plat — l'héritage : angles bruts, surfaces fondues",
    skin3dDepth: "3D — biseaux métal, cadran flottant, ombre papier",
    g1t: "CLOCK IN",
    g1b: "Les Seekers chassent. Nexus, c'est là où ils se trouvent. Punch prouve que tu es là.",
    g2t: "Un tap. Tu es là.",
    g2b: "Appuie sur l'horloge. Un vrai Seeker, pas un ordinateur.",
    g2go: "Touche l'éclair",
    g3t: "Ton ticket",
    g3b: "Le pays seulement. Jamais la rue. La part est écrite sur la carte.",
    g4t: "Qui garde quoi",
    g4b: "Touche chaque chiffre. Pas de frais caché.",
    g4w: "Toi — celui qui s'est présenté",
    g4s: "Ceux qui gardent du SKR",
    g4p: "Nexus — toi, le créateur",
    g5t: "Le monde",
    g5b: "Une pointe écrit un pays sur le globe. Tu le tournes. Pas de GPS.",
    g5go: "Tamponner la France",
    g6t: "Une mission, puis des dollars",
    g6b: "Quelques minutes. Payé en USDC ou USDT. Le reçu est public.",
    g7t: "Dire bonjour à côté",
    g7b: "Deux Seekers. Dix cents chacun, payés avec le 5 % de Nexus. Un salut, pas une ferme.",
    g7go: "Dire bonjour",
    g8t: "PLI, l'autre verbe",
    g8b: "Sceller des secrets — ça arrive après CLOCK IN.",
    genesis: "Ce Seeker est vérifié",
    punch: "Accueil",
    board: "Missions",
    wallet: "Argent",
    split: "La part",
    punchCta: "Je suis là",
    punched: "C'est noté",
    boardUnlocked: "Les missions sont ouvertes",
    streak: "Jours d'affilée",
    days: "jours",
    crew: "Personnes là",
    today: "Tu as gagné",
    nextWindow: "Prochain passage",
    demoNote: "Dans la démo tu peux revenir après une courte pause. En vrai : une fois par jour.",
    needPunch: "Appuie sur Je suis là pour voir les missions du jour.",
    earlyAccess: "Tu vois les missions un peu plus tôt",
    earlyAccessOff: "3 jours d'affilée = tu vois les missions en premier",
    rankLine: "Garder du SKR n'imprime pas d'argent. Ça te montre d'abord les missions mieux payées.",
    available: "Ouvert",
    locked: "Verrouillé",
    spots: "places",
    min: "min",
    startShift: "Faire cette mission",
    lockedRank: "Garde plus de SKR pour débloquer",
    lockedGenesis: "Il faut un vrai téléphone Seeker",
    posted: "Posté par toi",
    dwellCta: "Je suis arrivé",
    dwellHold: "Reste sur cet écran",
    reviewLabel: "Ce qui a vraiment marché ou cassé",
    reviewCta: "Envoyer ma note",
    reviewHint: "Au moins 40 caractères. Une étoile n'est pas un avis.",
    scanCta: "Scanner le code",
    scanStep1: "Vise le code",
    scanStep2: "Le téléphone prouve que c'est toi",
    scanStep3: "C'est confirmé",
    swapCta: "Faire l'échange",
    watchCta: "Lancer la veille",
    watchHold: "Garde cet écran ouvert",
    complete: "Être payé",
    signing: "Confirmation sur le téléphone…",
    cashed: "Payé",
    receipt: "Reçu",
    gross: "Total de la mission",
    worker: "Toi tu gardes",
    stakers: "Ceux qui gardent du SKR",
    protocol: "Cette app",
    tx: "Preuve",
    back: "Retour",
    postShift: "Payer quelqu'un",
    postTitle: "Payer une mission",
    postBody:
      "Tu bloques des dollars numériques. Quelqu'un avec un Seeker fait le travail. Même règle : 92 % pour lui, 3 % pour les gardes-SKR, 5 % pour l'app.",
    postCta: "Bloquer l'argent",
    title: "Titre de la mission",
    amount: "Paiement",
    token: "Monnaie",
    city: "Ville",
    duration: "Minutes",
    fill: "Quelqu'un va la prendre bientôt.",
    fillCta: "Faire comme si quelqu'un l'avait prise",
    balances: "Ton argent",
    stake: "Garder du SKR pour monter",
    unstake: "Relâcher du SKR",
    staked: "Gardé",
    liquid: "Dispo",
    rank: "Accès",
    swap: "Changer de monnaie",
    from: "De",
    to: "Vers",
    spread: "Frais 0,35 %",
    spreadSplit: "Les petits frais d'échange sont affichés avant. Moitié pour l'app, moitié pour ceux qui gardent du SKR.",
    youPay: "Tu paies",
    youGet: "Tu reçois",
    swapFee: "Frais d'échange",
    confirmSwap: "Échanger",
    stakeHint: "1 000 SKR = Silver. 5 000 = Gold. 25 000 = Guardian. Meilleures missions en premier — pas d'argent inventé.",
    confirmStake: "Garder du SKR",
    splitHero: "Tu gardes 92 %. Toujours.",
    splitBody:
      "Sur chaque mission payée : 92 % à la personne venue, 3 % à ceux qui gardent du SKR, 5 % à l'app (c'est le créateur). Pas de points. Pas de frais surprise.",
    protocolTreasury: "App (créateur)",
    stakerPool: "Gardiens SKR",
    skrBought: "SKR achetés avec les frais",
    yourWages: "On t'a payé",
    feeTable: "Chaque reçu",
    reset: "Recommencer la démo",
    pitch: "Comment on le présente",
    live: "Démo · en direct",
    demoDataNote:
      "Réseau de démo : les Seekers proches et le flux sont simulés. Pointages, paiements et soldes sont réels, on-chain.",
    seekerOnly: "Fait pour le téléphone Seeker",
    demoVault: "Portefeuille démo. Sur un vrai Seeker, c'est le téléphone qui signe.",
    copyAddr: "Copié",
    notEnough: "Pas assez d'argent",
    tooShort: "Un peu court",
    done: "C'est bon",
    emptyBoard: "Rien dans ce filtre.",
    filterAll: "Toutes",
    howTitle: "Trois gestes. C'est toute l'app.",
    how1b: "Un tap par jour. Ton Seeker prouve qu'une vraie personne s'est présentée — pas un robot sur un ordinateur.",
    how2b: "Confirme qu'un café est ouvert, écris un avis honnête, scanne un stand. Quelques minutes. Payé en dollars numériques.",
    how3b: "Tu gardes 92 %. Ceux qui gardent du SKR : 3 %. L'app : 5 %. Le reçu est public. Toi et le créateur gagnez tous les deux, sans tricher.",
    moneyUsdc: "USDC et USDT = des dollars numériques. Un jeton ≈ un dollar US.",
    moneySkr: "SKR = le jeton du téléphone Seeker. Le garder = voir les meilleures missions en premier. Ça n'imprime pas de salaire.",
    seeJobs: "Voir les missions du jour",
    nearby: "Seekers près de toi",
    greet: "Dire bonjour",
    greeted: "Salué",
    greetPay: "Vous gagnez tous les deux 0,10 $. Payé avec les 5 % de l'app — un vrai bonjour, pas une ferme à clics.",
    meters: "m",
    themeDark: "Sombre",
    themeLight: "Clair",
    themeGold: "Gold Seeker Premium",
    themeGoldLight: "Or clair",
    paySomeone: "Payer quelqu'un",
    studio: "Deux produits. Même règle d'argent.",
    studioTitle: "Deux verbes. Pas deux copies.",
    punchPick: "Ouvrir PUNCH",
    punchPickBody: "Tu te présentes. Tu es payé.",
    pliPick: "Ouvrir PLI",
    pliPickBody: "Tu caches un secret. On paie pour le lire. La chaîne ne le voit pas.",
    pliName: "PLI",
    pliTag: "Un secret avec un prix. La chaîne est aveugle.",
    pliBox: "Boîte",
    pliWrite: "Sceller",
    pliSealed: "Scellé",
    pliOpened: "Ouvert",
    pliWaiting: "Pas encore",
    pliOpenCta: "Payer pour lire",
    pliOpening: "Décachetement sur le téléphone…",
    pliRead: "Relire",
    pliPrice: "Prix pour ouvrir",
    pliFrom: "De",
    pliWriteTitle: "Sceller une note",
    pliWriteBody:
      "Écris quelque chose que seul un Seeker peut décacheter. Tu es payé quand quelqu'un l'achète. Même part : 92 / 3 / 5.",
    pliWriteCta: "Sceller et publier",
    pliWriteHint: "Au moins 24 caractères. Ce texte n'est jamais en clair sur la chaîne.",
    pliDelayNow: "S'ouvre maintenant",
    pliDelaySoon: "S'ouvre dans 1 min",
    pliMine: "Le tien",
    pliSold: "Quelqu'un a payé pour le lire",
    pliWaitingSell: "En attente d'un lecteur",
    pliLetter: "Décacheté",
    pliChain: "Solana a vu le paiement. Pas cette phrase.",
    pliEmpty: "Aucun pli ici.",
    pliSeeBox: "Retour à la boîte",
    pliSoon: "Reviens. Le sceau s'ouvre tout seul.",
    atelier: "Les deux apps",
    pliCompte: "Registre",
    pliConnectTitle: "La chaîne ne lira pas ça.",
    pliConnectCta: "Briser le cachet",
    punchEnter: "Entrer dans PUNCH",
    pliEnter: "Entrer dans PLI",
    globe: "Monde",
    globeTag: "Seekers certifiés. Pays seulement.",
    globePrivacy: "Une pointe écrit un pays. Jamais une rue. Jamais un GPS.",
    globeToday: "Pointés aujourd'hui",
    globeAll: "Genesis / Seekers",
    globeYou: "Tu es sur la carte",
    globeNeed: "Pointe pour tamponner ton pays.",
    globeStamp: "Tampon on-chain",
    globePick: "Ton pays (pas d'adresse)",
    seeWorld: "Voir le monde",
    globeLive: "Tampons live",
    punchCode: "Télécharger le code PUNCH",
    pliCode: "Télécharger le code PLI",
    settings: "Réglages",
    settingsLanguage: "Langue",
    settingsAppearance: "Apparence",
    settingsAccount: "Compte",
    settingsAbout: "À propos",
    settingsWalletMode: "Mode portefeuille",
    settingsWalletReal: "Seed Vault réel",
    settingsWalletDemo: "Portefeuille démo",
    settingsResetConfirm: "Réinitialiser toutes les données démo ? C'est irréversible.",
    settingsVersion: "Version",
    netSection: "Réseau",
    netTag: "Le RPC devnet public sature. Branche ton propre endpoint — tes clés ne quittent jamais ton téléphone.",
    netPlaceholder: "https://ton-endpoint.devnet...",
    netSave: "Enregistrer l'endpoint",
    netReset: "Revenir au RPC public",
    netTest: "Tester la connexion",
    netTesting: "Test en cours…",
    netOk: (ms: number) => `Connexion OK — ${ms} ms`,
    netFail: (why: string) => `Connexion échouée : ${why}`,
    netUsingCustom: "Endpoint personnalisé actif",
    netUsingDefault: "RPC public actif",
    netInvalid: "Entre une URL qui commence par https://",
    leaveNetwork: "Quitter le réseau",
    leaveNetworkConfirm:
      "Quitter le réseau ? Ça signe une vraie transaction. Tu ne seras plus compté, et il faudra te reconnecter (nouvelle transaction) pour revenir.",
    leaveNetworkFailed: "Transaction refusée ou échouée — rien n'a été réinitialisé.",
    leaveNetworkHint: "Nécessite une transaction Seed Vault signée pour confirmer ta sortie.",
    realTxHint: "Vraie transaction devnet — Seed Vault va te demander de signer.",
    txFailed: "Transaction refusée ou échouée — rien n'a changé.",
    needReconnect: "Session expirée — rouvre ton portefeuille pour signer.",
    needSol: "Pas assez de SOL dans ton portefeuille pour les frais réseau. Recharge et réessaie.",
    stakeLocked: "Mis sous séquestre",
    stakeFee: "Frais de retrait (1,5 %)",
    stakeNet: "Net libéré",
    tapToWake: "Touche pour réveiller",
    settingsScreensaver: "Veille — habillages",
    screensaverOff: "Off",
    screensaverSecs: (n: number) => `${n}s`,
    cancel: "Annuler",
    confirm: "Confirmer",
    hellos: "Bonjours",
    hellosTag: "Chaque bonjour compte. Ton cumul, semaine après semaine.",
    hellosWeek: "Cette semaine",
    hellosMonth: "Ce mois",
    hellosYear: "Cette année",
    hellosTotal: "Depuis le début",
    hellosBoard: "Classement des bonjours",
    hellosYou: "Toi",
    hellosEarned: "SKR gagnés en disant bonjour",
    hellosReward: "Chaque bonjour rapporte 25 SKR en plus de tes 0,10 $. Bonus de démarrage, pas encore on-chain — quand il le sera, ce sera une vraie transaction.",
    hellosEmpty: "Aucun bonjour pour l'instant. Dis bonjour à quelqu'un à côté.",
    hellosReset: "Compteurs remis à zéro lundi, le 1er et au 1er janvier.",
    history: "Historique des tickets",
    historyTag: "Chaque ticket reçu — touche pour le rouvrir.",
    historyEmpty: "Aucun ticket pour l'instant. Ta première mission ou ton premier bonjour arrivera ici.",
    stakerPaid: "Gardiens SKR — ta part",
    openRanks: {
      open: "Ouvert à tous",
      silver: "Argent",
      gold: "Or",
      guardian: "Gardien",
    },
    kinds: {
      dwell: "Être là",
      review: "Écrire",
      scan: "Scanner",
      swap: "Échanger",
      watch: "Veiller",
    },
  },
} as const;

export type Copy = (typeof copy)["en"];
