import type { FeedItem, Receipt, Shift } from "./types";

export const DEMO_ADDRESS = "7PunchK3mQvR9sW2nHf8aLcT4yE1dX6bUo0kR3";

export const NEARBY = [
  { id: "n-nao", name: "Nao", meters: 8 },
  { id: "n-ines", name: "Inès", meters: 40 },
  { id: "n-karim", name: "Karim", meters: 120 },
];

export const SHIFTS: Shift[] = [
  {
    id: "cafe-lumen",
    title: { en: "Confirm café is open", fr: "Confirmer le café ouvert" },
    sponsor: "Northside Roasters",
    city: { en: "Lisbon", fr: "Lisbonne" },
    kind: "dwell",
    durationMin: 12,
    payout: 4.2,
    token: "USDC",
    rank: "open",
    spots: 6,
    taken: 2,
    genesisRequired: false,
    blurb: {
      en: "Stand inside for a 12-min dwell. Seed Vault signs a presence proof. No photo of strangers.",
      fr: "Reste 12 min sur place. Le Seed Vault signe une preuve de présence. Pas de photo de passants.",
    },
  },
  {
    id: "review-moth",
    title: { en: "Honest dApp note", fr: "Note honnête d'une dApp" },
    sponsor: "Studio Moth",
    city: { en: "Remote", fr: "À distance" },
    kind: "review",
    durationMin: 8,
    payout: 2.5,
    token: "USDC",
    rank: "open",
    spots: 40,
    taken: 18,
    genesisRequired: false,
    blurb: {
      en: "Write what actually broke. Paid for specificity, not stars. Reviews shorter than 40 characters are rejected.",
      fr: "Écris ce qui casse vraiment. Payé pour la précision, pas les étoiles. Moins de 40 caractères = refusé.",
    },
  },
  {
    id: "swap-pulse",
    title: { en: "SKR pulse swap", fr: "Swap pulse SKR" },
    sponsor: "Punch Treasury",
    city: { en: "On-chain", fr: "On-chain" },
    kind: "swap",
    durationMin: 2,
    payout: 180,
    token: "SKR",
    rank: "silver",
    spots: 25,
    taken: 11,
    genesisRequired: false,
    blurb: {
      en: "Route a tiny SKR↔USDC swap through the published spread. You keep the wage. Spread is split in the open.",
      fr: "Passe un petit swap SKR↔USDC au spread publié. Tu gardes le salaire. Le spread est partagé à vue.",
    },
  },
  {
    id: "night-kl",
    title: { en: "Night market scan", fr: "Scan du marché de nuit" },
    sponsor: "Pasar Gate",
    city: { en: "Kuala Lumpur", fr: "Kuala Lumpur" },
    kind: "scan",
    durationMin: 20,
    payout: 7.8,
    token: "USDT",
    rank: "open",
    spots: 8,
    taken: 3,
    genesisRequired: true,
    blurb: {
      en: "Scan the stall QR. Seed Vault attests the device, not a screenshot. Genesis token required — bots don't hold one.",
      fr: "Scan le QR du stand. Le Seed Vault atteste l'appareil, pas un screenshot. Genesis requis — les bots n'en ont pas.",
    },
  },
  {
    id: "meetup-paris",
    title: { en: "Witness the meetup", fr: "Témoin du meetup" },
    sponsor: "Seeker Club Paris",
    city: { en: "Paris 11e", fr: "Paris 11e" },
    kind: "dwell",
    durationMin: 30,
    payout: 14,
    token: "USDC",
    rank: "gold",
    spots: 12,
    taken: 4,
    genesisRequired: true,
    blurb: {
      en: "Be in the room. Hardware attestation, not a check-in selfie. Gold rank sees this 15 minutes early.",
      fr: "Sois dans la salle. Attestation hardware, pas un selfie. Le rang Gold le voit 15 minutes plus tôt.",
    },
  },
  {
    id: "guardian-desk",
    title: { en: "Guardian desk watch", fr: "Veille Guardian" },
    sponsor: "Guardian Desk",
    city: { en: "On-device", fr: "Sur l'appareil" },
    kind: "watch",
    durationMin: 15,
    payout: 9.4,
    token: "USDC",
    rank: "guardian",
    spots: 4,
    taken: 1,
    genesisRequired: true,
    blurb: {
      en: "Hold a 15-min watch window. Flag one suspicious listing. Paid in USDC, gated by 25k staked SKR.",
      fr: "Tiens une fenêtre de 15 min. Signale une fiche douteuse. Payé en USDC, accès 25k SKR stakés.",
    },
  },
  {
    id: "roam-lagos",
    title: { en: "Corridor roam", fr: "Parcours corridor" },
    sponsor: "Open Guild",
    city: { en: "Lagos", fr: "Lagos" },
    kind: "dwell",
    durationMin: 18,
    payout: 6.1,
    token: "USDT",
    rank: "silver",
    spots: 10,
    taken: 6,
    genesisRequired: false,
    blurb: {
      en: "Walk the marked corridor. Presence pings every 90 seconds. Leave early and the escrow returns to the sponsor.",
      fr: "Marche le corridor marqué. Un ping toutes les 90 s. Tu pars tôt, l'escrow revient au sponsor.",
    },
  },
  {
    id: "stall-ba",
    title: { en: "Stall inventory tap", fr: "Inventaire stand" },
    sponsor: "Mercado Sur",
    city: { en: "Buenos Aires", fr: "Buenos Aires" },
    kind: "scan",
    durationMin: 10,
    payout: 3.9,
    token: "USDC",
    rank: "open",
    spots: 14,
    taken: 9,
    genesisRequired: false,
    blurb: {
      en: "Tap three stall codes. Merchant posted the USDC. If the codes don't match, you still get a 0.40 USDC show-up.",
      fr: "Tap trois codes de stand. Le commerçant a déposé l'USDC. Si ça ne match pas, 0.40 USDC de présentation.",
    },
  },
];

export const SEED_RECEIPTS: Receipt[] = [
  {
    id: "r-seed-1",
    at: Date.now() - 36e5 * 6,
    kind: "shift",
    title: "Confirm café is open",
    token: "USDC",
    gross: 4.2,
    worker: 3.86,
    stakers: 0.13,
    protocol: 0.21,
    signature: "5nQ2kPunchSeedVaultCafeLumen7xH9cR",
    city: "Lisbon",
  },
  {
    id: "r-seed-2",
    at: Date.now() - 36e5 * 22,
    kind: "shift",
    title: "Night market scan",
    token: "USDT",
    gross: 7.8,
    worker: 7.18,
    stakers: 0.23,
    protocol: 0.39,
    signature: "3bR8sPunchSeedVaultNightKL2mP4dW",
    city: "Kuala Lumpur",
  },
  {
    id: "r-seed-3",
    at: Date.now() - 36e5 * 48,
    kind: "swap",
    title: "SKR → USDC",
    token: "USDC",
    gross: 0.42,
    worker: 0,
    stakers: 0.21,
    protocol: 0.21,
    signature: "2kL9aPunchSwapSpreadSplit4sT8nQ",
  },
];

export const SEED_FEED: FeedItem[] = [
  {
    id: "f1",
    at: Date.now() - 40000,
    name: "Inès",
    text: { en: "punched in · Paris", fr: "a pointé · Paris" },
  },
  {
    id: "f2",
    at: Date.now() - 95000,
    name: "Karim",
    text: { en: "cleared a 7.80 USDT scan", fr: "a encaissé un scan 7.80 USDT" },
    amount: 7.18,
    token: "USDT",
  },
  {
    id: "f3",
    at: Date.now() - 140000,
    name: "Nao",
    text: { en: "staked 2,400 SKR to Gold", fr: "a staké 2 400 SKR · Gold" },
  },
];

export const FEED_POOL: Omit<FeedItem, "id" | "at">[] = [
  { name: "Léa", text: { en: "punched in · Lisbon", fr: "a pointé · Lisbonne" } },
  { name: "Jules", text: { en: "posted a 5.00 USDC shift", fr: "a posté un shift 5.00 USDC" } },
  {
    name: "Mira",
    text: { en: "cleared an honest review", fr: "a validé une note honnête" },
    amount: 2.3,
    token: "USDC",
  },
  { name: "Theo", text: { en: "punched in · Lagos", fr: "a pointé · Lagos" } },
  {
    name: "Amina",
    text: { en: "took Guardian desk watch", fr: "a pris la veille Guardian" },
    amount: 8.65,
    token: "USDC",
  },
  { name: "Rafi", text: { en: "swapped SKR → USDC, spread shown", fr: "a swappé SKR → USDC, spread affiché" } },
  { name: "Sofia", text: { en: "punched in · Buenos Aires", fr: "a pointé · Buenos Aires" } },
  {
    name: "Owen",
    text: { en: "cleared café dwell", fr: "a validé le dwell café" },
    amount: 3.86,
    token: "USDC",
  },
];
