/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ARouteImport } from './routes/a'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as BRouteImport } from './routes/b'
import { Route as CRouteImport } from './routes/c'
import { Route as LooksRouteImport } from './routes/looks'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as PliRouteImport } from './routes/pli'
import { Route as PunchRouteImport } from './routes/punch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ARoute = ARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const BRoute = BRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any)
const CRoute = CRouteImport.update({
  id: '/c',
  path: '/c',
  getParentRoute: () => rootRouteImport,
} as any)
const LooksRoute = LooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const PliRoute = PliRouteImport.update({
  id: '/pli',
  path: '/pli',
  getParentRoute: () => rootRouteImport,
} as any)
const PunchRoute = PunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a': typeof ARoute
  '/apps': typeof AppsRoute
  '/b': typeof BRoute
  '/c': typeof CRoute
  '/looks': typeof LooksRoute
  '/pitch': typeof PitchRoute
  '/pli': typeof PliRoute
  '/punch': typeof PunchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a': typeof ARoute
  '/apps': typeof AppsRoute
  '/b': typeof BRoute
  '/c': typeof CRoute
  '/looks': typeof LooksRoute
  '/pitch': typeof PitchRoute
  '/pli': typeof PliRoute
  '/punch': typeof PunchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a': typeof ARoute
  '/apps': typeof AppsRoute
  '/b': typeof BRoute
  '/c': typeof CRoute
  '/looks': typeof LooksRoute
  '/pitch': typeof PitchRoute
  '/pli': typeof PliRoute
  '/punch': typeof PunchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/a' | '/apps' | '/b' | '/c' | '/looks' | '/pitch' | '/pli' | '/punch'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/a' | '/apps' | '/b' | '/c' | '/looks' | '/pitch' | '/pli' | '/punch'
  id:
    | '__root__'
    | '/'
    | '/a'
    | '/apps'
    | '/b'
    | '/c'
    | '/looks'
    | '/pitch'
    | '/pli'
    | '/punch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ARoute: typeof ARoute
  AppsRoute: typeof AppsRoute
  BRoute: typeof BRoute
  CRoute: typeof CRoute
  LooksRoute: typeof LooksRoute
  PitchRoute: typeof PitchRoute
  PliRoute: typeof PliRoute
  PunchRoute: typeof PunchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a': {
      id: '/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof ARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c': {
      id: '/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks': {
      id: '/looks'
      path: '/looks'
      fullPath: '/looks'
      preLoaderRoute: typeof LooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pli': {
      id: '/pli'
      path: '/pli'
      fullPath: '/pli'
      preLoaderRoute: typeof PliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punch': {
      id: '/punch'
      path: '/punch'
      fullPath: '/punch'
      preLoaderRoute: typeof PunchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ARoute: ARoute,
  AppsRoute: AppsRoute,
  BRoute: BRoute,
  CRoute: CRoute,
  LooksRoute: LooksRoute,
  PitchRoute: PitchRoute,
  PliRoute: PliRoute,
  PunchRoute: PunchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
