export const copy = {
  en: {
    app: "PUNCH",
    tag: "Show up. Get paid. See who keeps what.",
    connectTitle: "Get paid to show up.",
    connectBody:
      "Small real-world jobs on your Seeker phone. You are paid in digital dollars. Everyone sees the cut. No hidden fee.",
    connectCta: "Open my wallet",
    connecting: "Opening wallet…",
    genesis: "This Seeker is verified",
    punch: "Home",
    board: "Jobs",
    wallet: "Money",
    split: "The cut",
    punchCta: "I'm here",
    punched: "You're in",
    boardUnlocked: "Jobs are open",
    streak: "Days in a row",
    days: "days",
    crew: "People here",
    today: "You earned",
    nextWindow: "Next check-in",
    demoNote: "In this demo you can check in again after a short wait. For real: once a day.",
    needPunch: "Tap I'm here to unlock today's jobs.",
    earlyAccess: "You see jobs a bit earlier",
    earlyAccessOff: "3 days in a row = you see jobs first",
    rankLine: "Keeping SKR does not print money. It lets you see the better-paid jobs first.",
    available: "Open",
    locked: "Locked",
    spots: "spots left",
    min: "min",
    startShift: "Do this job",
    lockedRank: "Keep more SKR to unlock",
    lockedGenesis: "Needs a real Seeker phone",
    posted: "You posted this",
    dwellCta: "I arrived",
    dwellHold: "Stay on this screen",
    reviewLabel: "What really worked or broke",
    reviewCta: "Send my note",
    reviewHint: "Write at least 40 characters. A star is not a review.",
    scanCta: "Scan the code",
    scanStep1: "Point at the code",
    scanStep2: "Phone is proving it's you",
    scanStep3: "You're confirmed",
    swapCta: "Make the exchange",
    watchCta: "Start the watch",
    watchHold: "Keep this screen open",
    complete: "Get paid",
    signing: "Confirming on the phone…",
    cashed: "Paid",
    receipt: "Receipt",
    gross: "Job total",
    worker: "You keep",
    stakers: "SKR holders",
    protocol: "This app",
    tx: "Proof",
    back: "Back",
    postShift: "Pay someone",
    postTitle: "Pay for a job",
    postBody:
      "You lock digital dollars. Someone with a Seeker does the job. Same rule: they keep 92%, holders 3%, the app 5%.",
    postCta: "Lock the money",
    title: "Job title",
    amount: "Pay",
    token: "Currency",
    city: "City",
    duration: "Minutes",
    fill: "Someone will take this soon.",
    fillCta: "Pretend someone took it",
    balances: "Your money",
    stake: "Keep SKR to rank up",
    unstake: "Release SKR",
    staked: "Kept",
    liquid: "Ready to use",
    rank: "Access",
    swap: "Change currency",
    from: "From",
    to: "To",
    spread: "Fee 0.35%",
    spreadSplit: "The small exchange fee is shown first. Half to the app, half to SKR holders.",
    youPay: "You pay",
    youGet: "You receive",
    confirmSwap: "Exchange",
    stakeHint: "1,000 SKR = Silver. 5,000 = Gold. 25,000 = Guardian. Better jobs first — no extra printed money.",
    confirmStake: "Keep SKR",
    splitHero: "You keep 92%. Always.",
    splitBody:
      "On every paid job: 92% to the person who showed up, 3% to people who keep SKR, 5% to the app (that's the creator). No points. No surprise fee.",
    protocolTreasury: "App (creator)",
    stakerPool: "SKR holders",
    skrBought: "Dollars used to buy SKR",
    yourWages: "You were paid",
    feeTable: "Every receipt",
    reset: "Start the demo over",
    pitch: "How we present it",
    live: "Right now",
    seekerOnly: "Made for the Seeker phone",
    demoVault: "Demo wallet. On a real Seeker the phone itself signs.",
    copyAddr: "Copied",
    notEnough: "Not enough money",
    tooShort: "A bit short",
    done: "Done",
    emptyBoard: "Nothing in this filter.",
    filterAll: "All",
    howTitle: "Three steps. That's the whole app.",
    how1t: "1. Say you're here",
    how1b: "One tap a day. Your Seeker proves a real person showed up — not a robot on a laptop.",
    how2t: "2. Do a short job",
    how2b: "Confirm a café is open, write an honest note, scan a stall. A few minutes. Paid in digital dollars.",
    how3t: "3. See the cut",
    how3b: "You keep 92%. SKR holders get 3%. The app keeps 5%. The receipt is public. That's how you and the creator both earn, honestly.",
    howCta: "Got it — I'm here",
    moneyUsdc: "USDC and USDT are digital dollars. One token ≈ one US dollar.",
    moneySkr: "SKR is the Seeker phone token. Keep it to see better jobs first. It does not print extra pay.",
    seeJobs: "See today's jobs",
    nearby: "Seekers near you",
    greet: "Say hi",
    greeted: "Said hi",
    greetPay: "You both get $0.10. Paid from the app's 5% — a hello, not a farm.",
    meters: "m away",
    themeDark: "Dark",
    themeLight: "Light",
    paySomeone: "Pay someone",
    studio: "Two products. Same money rule.",
    studioTitle: "Two verbs. Not two copies.",
    punchPick: "Open PUNCH",
    punchPickBody: "You show up. You get paid.",
    pliPick: "Open PLI",
    pliPickBody: "You seal a secret. People pay to read it. The chain never does.",
    pliName: "PLI",
    pliTag: "A secret with a price. The chain is blind.",
    pliBox: "Inbox",
    pliWrite: "Seal",
    pliSealed: "Sealed",
    pliOpened: "Opened",
    pliWaiting: "Not yet",
    pliOpenCta: "Pay to read",
    pliOpening: "Unsealing on the phone…",
    pliRead: "Read again",
    pliPrice: "Price to open",
    pliFrom: "From",
    pliWriteTitle: "Seal a note",
    pliWriteBody:
      "Write something only a Seeker can unwrap. You are paid when someone buys it. Same cut: 92 / 3 / 5.",
    pliWriteCta: "Seal and list",
    pliWriteHint: "At least 24 characters. This text never sits in clear on the chain.",
    pliDelayNow: "Opens now",
    pliDelaySoon: "Opens in 1 min",
    pliMine: "Yours",
    pliSold: "Someone paid to read this",
    pliWaitingSell: "Waiting for a reader",
    pliLetter: "Unsealed",
    pliChain: "Solana saw the payment. It did not see this sentence.",
    pliEmpty: "No sealed notes here.",
    pliSeeBox: "Back to inbox",
    pliSoon: "Come back. The seal opens on its own.",
    atelier: "Both apps",
    pliCompte: "Ledger",
    pliConnectTitle: "The chain will not read this.",
    pliConnectCta: "Break the seal",
    punchEnter: "Enter PUNCH",
    pliEnter: "Enter PLI",
    globe: "World",
    globeTag: "Certified Seekers. Country only.",
    globePrivacy: "A punch writes a country. Never a street. Never a GPS point.",
    globeToday: "Punched today",
    globeAll: "Genesis / Seekers",
    globeYou: "You are on the map",
    globeNeed: "Punch in to stamp your country.",
    globeStamp: "On-chain stamp",
    globePick: "Your country (no address)",
    seeWorld: "See the world",
    globeLive: "Live stamps",
    punchCode: "Download PUNCH source",
    pliCode: "Download PLI source",
    clockIn: "CLOCK IN",
    nexusLine: "Nexus pays presence.",
    ticketIn: "IN",
    ticketRule: "92 / 3 / 5 on every job",
    guideSkip: "Skip — open the apps",
    guideNext: "Next",
    guideBack: "Back",
    guideStart: "Start the tour",
    guideDone: "That's the whole app",
    g1t: "CLOCK IN",
    g1b: "Seekers hunt. Nexus is where they meet. Punch proves you showed up.",
    g2t: "One tap. You're here.",
    g2b: "Press the clock. A real Seeker, not a laptop.",
    g2go: "Tap the bolt",
    g3t: "Your ticket",
    g3b: "Country only. Never a street. The cut is printed on the card.",
    g4t: "Who keeps what",
    g4b: "Tap each number. No hidden fee.",
    g4w: "You — the person who showed up",
    g4s: "People who keep SKR",
    g4p: "Nexus — you, the creator",
    g5t: "The world",
    g5b: "A punch writes a country on the globe. Drag it. No GPS.",
    g5go: "Stamp France",
    g6t: "A job, then dollars",
    g6b: "A few minutes. Paid in USDC or USDT. Receipt is public.",
    g7t: "Say hi nearby",
    g7b: "Two Seekers. Ten cents each, paid from Nexus's 5%. A hello, not a farm.",
    g7go: "Say hi",
    g8t: "PLI is the other verb",
    g8b: "Seal a secret. People pay to read it. The chain stays blind. Ships after CLOCK IN.",
    g8go: "Seal",
    openRanks: {
      open: "Open to all",
      silver: "Silver",
      gold: "Gold",
      guardian: "Guardian",
    },
    kinds: {
      dwell: "Be there",
      review: "Write",
      scan: "Scan",
      swap: "Exchange",
      watch: "Watch",
    },
  },
  fr: {
    app: "PUNCH",
    tag: "Tu te présentes. Tu es payé. On voit qui garde quoi.",
    connectTitle: "Sois là. Sois payé.",
    connectBody:
      "De petites missions autour de toi, sur le téléphone Seeker. Tu es payé en dollars numériques. La commission est affichée. Rien n’est caché.",
    connectCta: "Ouvrir mon portefeuille",
    connecting: "Ouverture du portefeuille…",
    genesis: "Ce Seeker est vérifié",
    punch: "Accueil",
    board: "Missions",
    wallet: "Argent",
    split: "La part",
    punchCta: "Je suis là",
    punched: "C’est noté",
    boardUnlocked: "Les missions sont ouvertes",
    streak: "Jours d’affilée",
    days: "jours",
    crew: "Personnes là",
    today: "Tu as gagné",
    nextWindow: "Prochain passage",
    demoNote: "Dans la démo tu peux revenir après une courte pause. En vrai : une fois par jour.",
    needPunch: "Appuie sur Je suis là pour voir les missions du jour.",
    earlyAccess: "Tu vois les missions un peu plus tôt",
    earlyAccessOff: "3 jours d’affilée = tu vois les missions en premier",
    rankLine: "Garder du SKR n’imprime pas d’argent. Ça te montre d’abord les missions mieux payées.",
    available: "Ouvert",
    locked: "Verrouillé",
    spots: "places",
    min: "min",
    startShift: "Faire cette mission",
    lockedRank: "Garde plus de SKR pour débloquer",
    lockedGenesis: "Il faut un vrai téléphone Seeker",
    posted: "Posté par toi",
    dwellCta: "Je suis arrivé",
    dwellHold: "Reste sur cet écran",
    reviewLabel: "Ce qui a vraiment marché ou cassé",
    reviewCta: "Envoyer ma note",
    reviewHint: "Au moins 40 caractères. Une étoile n’est pas un avis.",
    scanCta: "Scanner le code",
    scanStep1: "Vise le code",
    scanStep2: "Le téléphone prouve que c’est toi",
    scanStep3: "C’est confirmé",
    swapCta: "Faire l’échange",
    watchCta: "Lancer la veille",
    watchHold: "Garde cet écran ouvert",
    complete: "Être payé",
    signing: "Confirmation sur le téléphone…",
    cashed: "Payé",
    receipt: "Reçu",
    gross: "Total de la mission",
    worker: "Toi tu gardes",
    stakers: "Ceux qui gardent du SKR",
    protocol: "Cette app",
    tx: "Preuve",
    back: "Retour",
    postShift: "Payer quelqu’un",
    postTitle: "Payer une mission",
    postBody:
      "Tu bloques des dollars numériques. Quelqu’un avec un Seeker fait le travail. Même règle : 92 % pour lui, 3 % pour les gardes-SKR, 5 % pour l’app.",
    postCta: "Bloquer l’argent",
    title: "Titre de la mission",
    amount: "Paiement",
    token: "Monnaie",
    city: "Ville",
    duration: "Minutes",
    fill: "Quelqu’un va la prendre bientôt.",
    fillCta: "Faire comme si quelqu’un l’avait prise",
    balances: "Ton argent",
    stake: "Garder du SKR pour monter",
    unstake: "Relâcher du SKR",
    staked: "Gardé",
    liquid: "Dispo",
    rank: "Accès",
    swap: "Changer de monnaie",
    from: "De",
    to: "Vers",
    spread: "Frais 0,35 %",
    spreadSplit: "Les petits frais d’échange sont affichés avant. Moitié pour l’app, moitié pour ceux qui gardent du SKR.",
    youPay: "Tu paies",
    youGet: "Tu reçois",
    confirmSwap: "Échanger",
    stakeHint: "1 000 SKR = Silver. 5 000 = Gold. 25 000 = Guardian. Meilleures missions en premier — pas d’argent inventé.",
    confirmStake: "Garder du SKR",
    splitHero: "Tu gardes 92 %. Toujours.",
    splitBody:
      "Sur chaque mission payée : 92 % à la personne venue, 3 % à ceux qui gardent du SKR, 5 % à l’app (c’est le créateur). Pas de points. Pas de frais surprise.",
    protocolTreasury: "App (créateur)",
    stakerPool: "Gardiens SKR",
    skrBought: "Dollars utilisés pour acheter du SKR",
    yourWages: "On t’a payé",
    feeTable: "Chaque reçu",
    reset: "Recommencer la démo",
    pitch: "Comment on le présente",
    live: "En ce moment",
    seekerOnly: "Fait pour le téléphone Seeker",
    demoVault: "Portefeuille démo. Sur un vrai Seeker, c’est le téléphone qui signe.",
    copyAddr: "Copié",
    notEnough: "Pas assez d’argent",
    tooShort: "Un peu court",
    done: "C’est bon",
    emptyBoard: "Rien dans ce filtre.",
    filterAll: "Toutes",
    howTitle: "Trois gestes. C’est toute l’app.",
    how1t: "1. Dis que tu es là",
    how1b: "Un tap par jour. Ton Seeker prouve qu’une vraie personne s’est présentée — pas un robot sur un ordinateur.",
    how2t: "2. Fais une courte mission",
    how2b: "Confirme qu’un café est ouvert, écris un avis honnête, scanne un stand. Quelques minutes. Payé en dollars numériques.",
    how3t: "3. Vois la part de chacun",
    how3b: "Tu gardes 92 %. Ceux qui gardent du SKR : 3 %. L’app : 5 %. Le reçu est public. Toi et le créateur gagnez tous les deux, sans tricher.",
    howCta: "C’est compris — je suis là",
    moneyUsdc: "USDC et USDT = des dollars numériques. Un jeton ≈ un dollar US.",
    moneySkr: "SKR = le jeton du téléphone Seeker. Le garder = voir les meilleures missions en premier. Ça n’imprime pas de salaire.",
    seeJobs: "Voir les missions du jour",
    nearby: "Seekers près de toi",
    greet: "Dire bonjour",
    greeted: "Salué",
    greetPay: "Vous gagnez tous les deux 0,10 $. Payé avec les 5 % de l’app — un vrai bonjour, pas une ferme à clics.",
    meters: "m",
    themeDark: "Sombre",
    themeLight: "Clair",
    paySomeone: "Payer quelqu’un",
    studio: "Deux produits. Même règle d’argent.",
    studioTitle: "Deux verbes. Pas deux copies.",
    punchPick: "Ouvrir PUNCH",
    punchPickBody: "Tu te présentes. Tu es payé.",
    pliPick: "Ouvrir PLI",
    pliPickBody: "Tu caches un secret. On paie pour le lire. La chaîne ne le voit pas.",
    pliName: "PLI",
    pliTag: "Un secret avec un prix. La chaîne est aveugle.",
    pliBox: "Boîte",
    pliWrite: "Sceller",
    pliSealed: "Scellé",
    pliOpened: "Ouvert",
    pliWaiting: "Pas encore",
    pliOpenCta: "Payer pour lire",
    pliOpening: "Décachetement sur le téléphone…",
    pliRead: "Relire",
    pliPrice: "Prix pour ouvrir",
    pliFrom: "De",
    pliWriteTitle: "Sceller une note",
    pliWriteBody:
      "Écris quelque chose que seul un Seeker peut décacheter. Tu es payé quand quelqu’un l’achète. Même part : 92 / 3 / 5.",
    pliWriteCta: "Sceller et publier",
    pliWriteHint: "Au moins 24 caractères. Ce texte n’est jamais en clair sur la chaîne.",
    pliDelayNow: "S’ouvre maintenant",
    pliDelaySoon: "S’ouvre dans 1 min",
    pliMine: "Le tien",
    pliSold: "Quelqu’un a payé pour le lire",
    pliWaitingSell: "En attente d’un lecteur",
    pliLetter: "Décacheté",
    pliChain: "Solana a vu le paiement. Pas cette phrase.",
    pliEmpty: "Aucun pli ici.",
    pliSeeBox: "Retour à la boîte",
    pliSoon: "Reviens. Le sceau s’ouvre tout seul.",
    atelier: "Les deux apps",
    pliCompte: "Registre",
    pliConnectTitle: "La chaîne ne lira pas ça.",
    pliConnectCta: "Briser le cachet",
    punchEnter: "Entrer dans PUNCH",
    pliEnter: "Entrer dans PLI",
    globe: "Monde",
    globeTag: "Seekers certifiés. Pays seulement.",
    globePrivacy: "Une pointe écrit un pays. Jamais une rue. Jamais un GPS.",
    globeToday: "Pointés aujourd’hui",
    globeAll: "Genesis / Seekers",
    globeYou: "Tu es sur la carte",
    globeNeed: "Pointe pour tamponner ton pays.",
    globeStamp: "Tampon on-chain",
    globePick: "Ton pays (pas d’adresse)",
    seeWorld: "Voir le monde",
    globeLive: "Tampons live",
    punchCode: "Télécharger le code PUNCH",
    pliCode: "Télécharger le code PLI",
    clockIn: "CLOCK IN",
    nexusLine: "Nexus paie la présence.",
    ticketIn: "IN",
    ticketRule: "92 / 3 / 5 sur chaque mission",
    guideSkip: "Passer — ouvrir les apps",
    guideNext: "Suivant",
    guideBack: "Retour",
    guideStart: "Commencer le mode d’emploi",
    guideDone: "C’est toute l’app",
    g1t: "CLOCK IN",
    g1b: "Les Seekers chassent. Nexus, c’est là où ils se trouvent. Punch prouve que tu es là.",
    g2t: "Un tap. Tu es là.",
    g2b: "Appuie sur l’horloge. Un vrai Seeker, pas un ordinateur.",
    g2go: "Touche l’éclair",
    g3t: "Ton ticket",
    g3b: "Le pays seulement. Jamais la rue. La part est écrite sur la carte.",
    g4t: "Qui garde quoi",
    g4b: "Touche chaque chiffre. Pas de frais caché.",
    g4w: "Toi — celui qui s’est présenté",
    g4s: "Ceux qui gardent du SKR",
    g4p: "Nexus — toi, le créateur",
    g5t: "Le monde",
    g5b: "Une pointe écrit un pays sur le globe. Tu le tournes. Pas de GPS.",
    g5go: "Tamponner la France",
    g6t: "Une mission, puis des dollars",
    g6b: "Quelques minutes. Payé en USDC ou USDT. Le reçu est public.",
    g7t: "Dire bonjour à côté",
    g7b: "Deux Seekers. Dix cents chacun, payés avec le 5 % de Nexus. Un salut, pas une ferme.",
    g7go: "Dire bonjour",
    g8t: "PLI, l’autre verbe",
    g8b: "Tu scelles un secret. On paie pour le lire. La chaîne est aveugle. Ça sort après CLOCK IN.",
    g8go: "Sceller",
    openRanks: {
      open: "Ouvert à tous",
      silver: "Silver",
      gold: "Gold",
      guardian: "Guardian",
    },
    kinds: {
      dwell: "Être là",
      review: "Écrire",
      scan: "Scanner",
      swap: "Échanger",
      watch: "Veiller",
    },
  },
} as const;

export type Copy = (typeof copy)["en"];
